version: 2


jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/google-test-example
   
    steps:
      - checkout
      - save_cache:
          key: google-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/google-test-example

  
  bundle_dependencies:
    working_directory: ~/google-test-example  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - google-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - google-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: google-bundle-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/google-test-example/vendor/bundle
      - save_cache:
          key: google-bundle-{{ .Branch }}
          paths: 
            - ~/google-test-example/vendor/bundle
  
  code_analyzer:
    working_directory: ~/google-test-example  
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - restore_cache:
          keys:
            - google-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - google-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: Rubocop analyzer
          command: bundle exec rubocop

  chrome_test:
    working_directory: ~/google-test-example
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - restore_cache:
          keys:
            - google-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - google-bundle-{{ .Branch }}
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios (except @wip tags) on Goole Chrome browser
          command: |
            mkdir /tmp/test-results
            bundle exec cucumber --format junit --out /tmp/test-results/junit.xml
      - store_test_results:
          path: /tmp/test-results/junit.xml
      - store_artifacts:
          path: /tmp/test-results/junit.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires: 
            - checkout_code
      - code_analyzer:
          requires:
            - bundle_dependencies
      - chrome_test:
          requires:
            - bundle_dependencies
            - code_analyzer